# Generated by Django 3.0.3 on 2020-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=25, verbose_name='Отправитель')),
                ('reciever', models.CharField(max_length=25, verbose_name='Получатель')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('message_image', models.ImageField(blank=True, upload_to='images/task/', verbose_name='Изображение')),
                ('message_time', models.DateTimeField(verbose_name='Время отправления')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
