# Generated by Django 3.0.3 on 2020-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_auto_20200412_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_visibility',
            field=models.BooleanField(default=True, verbose_name='Отображение у получателя'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_visibility',
            field=models.BooleanField(default=True, verbose_name='Отображение у отправителя'),
        ),
    ]
