# Generated by Django 3.0.3 on 2020-06-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0005_auto_20200604_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_visibility',
            new_name='reciever_visibility',
        ),
    ]
