# Generated by Django 3.0.3 on 2020-04-07 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('post_text', models.TextField(verbose_name='Текст поста')),
                ('post_image', models.ImageField(blank=True, upload_to='images/post/', verbose_name='Изображение поста')),
                ('post_time', models.DateTimeField(verbose_name='Время создания')),
                ('post_like', models.IntegerField(default=0, verbose_name='Лайк')),
                ('post_dislike', models.IntegerField(default=0, verbose_name='Дизлайк')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislake'), (None, 'None')], default=None, max_length=7)),
                ('for_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
