# Generated by Django 3.0.3 on 2020-04-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200408_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_or_dislike',
            field=models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7),
        ),
    ]
