# Generated by Django 3.0.3 on 2020-05-02 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20200426_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_dislike',
        ),
        migrations.AddField(
            model_name='post',
            name='post_dislike',
            field=models.ManyToManyField(blank=True, related_name='post_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_like',
        ),
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='post_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
