# Generated by Django 3.0.3 on 2020-05-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200502_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image_url',
            field=models.ImageField(blank=True, upload_to='', verbose_name='URL изображения поста'),
        ),
    ]
