# Generated by Django 3.0.3 on 2020-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, verbose_name='Пользователь')),
                ('users_friend', models.CharField(max_length=25, verbose_name='Друг')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
            ],
            options={
                'verbose_name': 'Друг',
                'verbose_name_plural': 'Друзья',
            },
        ),
    ]
