# Generated by Django 3.0.3 on 2020-05-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200526_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
        migrations.AlterField(
            model_name='status',
            name='online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Был в онлайне'),
        ),
    ]
